version: "3.8"
services:

  eureka:
    build: ./eureka
    image: eureka
    container_name: eureka
    restart: on-failure
    tty: true
    networks:
      - microservices
    ports:
      - 8761:8761
    environment:
      KEYSTORE: /etc/keystore/eureka.keystore.p12
      KEYSTORE_PASSWORD: password
      KEYSTORE_ALIAS: eureka
      TRUSTSTORE: /etc/keystore/eureka.truststore.p12
      TRUSTSTORE_PASSWORD: password
    volumes:
      - ./certs/eureka/keystore:/etc/keystore

  zuul:
    build: ./microservices-app
    image: zuul
    container_name: zuul
    restart: on-failure
    tty: true
    networks:
      - microservices
    ports:
      - 8082:8082
    environment:
      REGISTRY_HOST: eureka
      REGISTRY_PORT: 8761
      KEYSTORE: /etc/keystore/zuul.keystore.p12
      KEYSTORE_PASSWORD: password
      KEYSTORE_ALIAS: zuul
      TRUSTSTORE: /etc/keystore/zuul.truststore.p12
      TRUSTSTORE_PASSWORD: password
    tty: true
    volumes:
      - ./certs/zuul/keystore:/etc/keystore
    depends_on:
      - eureka

  postgres:
    build: ./postgres
    container_name: postgres
    restart: always
    networks:
      - microservices
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: microservices
    volumes:
      - postgres-data:/var/lib/postgres

  advertisement:
    build: ./advertisement-service
    image: advertisement
    container_name: advertisement
    restart: on-failure
    networks:
      - microservices
    ports:
      - 8083:8083
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: postgres
      DATABASE_PORT: 5432
      DATABASE_DB: microservices
      DATABASE_SCHEMA: advertisement
      REGISTRY_HOST: eureka
      REGISTRY_PORT: 8761
      KEYSTORE: /etc/keystore/advertisement.keystore.p12
      KEYSTORE_PASSWORD: password
      KEYSTORE_ALIAS: advertisement
      TRUSTSTORE: /etc/keystore/advertisement.truststore.p12
      TRUSTSTORE_PASSWORD: password
    tty: true
    volumes:
      - ./certs/advertisement/keystore:/etc/keystore
    depends_on: 
      - postgres
      - eureka

  messages:
    build: ./message-service
    image: messages
    container_name: messages
    restart: on-failure
    networks:
      - microservices
    ports:
      - 8085:8085
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: postgres
      DATABASE_PORT: 5432
      DATABASE_DB: microservices
      DATABASE_SCHEMA: messages
      REGISTRY_HOST: eureka
      REGISTRY_PORT: 8761
      KEYSTORE: /etc/keystore/message.keystore.p12
      KEYSTORE_PASSWORD: password
      KEYSTORE_ALIAS: message
      TRUSTSTORE: /etc/keystore/message.truststore.p12
      TRUSTSTORE_PASSWORD: password
    tty: true
    volumes:
      - ./certs/message/keystore:/etc/keystore
    depends_on: 
      - postgres
      - eureka

  auth:
    build: ./auth-service
    image: auth
    container_name: auth
    restart: on-failure
    networks:
      - microservices
    ports:
      - 8084:8084
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: postgres
      DATABASE_PORT: 5432
      DATABASE_DB: microservices
      DATABASE_SCHEMA: users
      REGISTRY_HOST: eureka
      REGISTRY_PORT: 8761
      RMQ_HOST: rabbitmq-broker
      RMQ_PORT: 5671
      KEYSTORE: /etc/keystore/auth.keystore.p12
      KEYSTORE_PASSWORD: password
      KEYSTORE_ALIAS: auth
      TRUSTSTORE: /etc/keystore/auth.truststore.p12
      TRUSTSTORE_PASSWORD: password
    tty: true
    volumes:
      - ./certs/auth/keystore:/etc/keystore
    depends_on: 
      - postgres
      - eureka
      - rabbitmq-broker

  orders:
    build: ./orders-service
    image: orders
    container_name: orders
    restart: on-failure
    networks:
      - microservices
    ports:
      - 8072:8072
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: postgres
      DATABASE_PORT: 5432
      DATABASE_DB: microservices
      DATABASE_SCHEMA: orders
      REGISTRY_HOST: eureka
      REGISTRY_PORT: 8761
      KEYSTORE: /etc/keystore/order.keystore.p12
      KEYSTORE_PASSWORD: password
      KEYSTORE_ALIAS: order
      TRUSTSTORE: /etc/keystore/order.truststore.p12
      TRUSTSTORE_PASSWORD: password
    tty: true
    volumes:
      - ./certs/order/keystore:/etc/keystore
    tty: true
    depends_on: 
      - postgres
      - eureka

  email-service:
    build: ./email-service
    image: email-service
    container_name: email-service
    restart: on-failure
    tty: true
    networks:
      - microservices
    ports:
      - 8086:8086
    environment:
      RMQ_HOST: rabbitmq-broker
      RMQ_PORT: 5671     
      KEYSTORE: /etc/keystore/message.keystore.p12
      KEYSTORE_PASSWORD: password
      KEYSTORE_ALIAS: message
      TRUSTSTORE: /etc/keystore/message.truststore.p12
      TRUSTSTORE_PASSWORD: password
    depends_on:
      - rabbitmq-broker
    volumes:
      - ./certs/message/keystore:/etc/keystore

  rabbitmq-broker:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-broker
    ports:
      - 5672:5672
      - 5671:5671
      - 15671:15671
    environment:
      RABBITMQ_SSL_CACERTFILE: /etc/keystore/tls-ca-chain.pem
      RABBITMQ_SSL_CERTFILE: /etc/keystore/rabbitmq.crt
      RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT: "true"
      RABBITMQ_SSL_KEYFILE: /etc/keystore/rabbitmq.key
      RABBITMQ_SSL_VERIFY: verify_peer
    networks:
      - microservices
    volumes:
      - ./certs/rabbitmq:/etc/keystore
      

#AGENTSKA APLIKACIJA
  agent:
    build: ./agentska-aplikacija
    image: agent
    container_name: agent
    restart: on-failure
    networks:
      - microservices
    ports:
      - 8099:8099
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: postgres_agent
      DATABASE_PORT: 5432
      DATABASE_DB: agent_back
      REGISTRY_HOST: eureka
      KEYSTORE: /etc/keystore/auth.keystore.p12
      KEYSTORE_PASSWORD: password
      KEYSTORE_ALIAS: auth
      TRUSTSTORE: /etc/keystore/auth.truststore.p12
      TRUSTSTORE_PASSWORD: password
    tty: true
    volumes:
      - ./certs/auth/keystore:/etc/keystore
    depends_on: 
      - postgres_agent


  postgres_agent:
    image: postgres
    container_name: postgres_agent
    restart: always
    networks:
      - microservices
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: agent_back
    volumes:
      - postgres_agent-data:/var/lib/postgres_agent

networks:
  microservices:
    name: microservices
    driver: bridge

volumes:
  postgres-data:
  postgres_agent-data:

networks:
  microservices:
    name: microservices
    driver: bridge
