spring:
  application:
    # sets the name in Eureka
    name: ${springboot.app.name:eureka-serviceregistry}

server:
  port: 8761
  #ssl:
  #  algorithm: ${TLS_VERSION:TLSv1.2}
  #  key-store: ${KEYSTORE:src/main/resources/eureka.keystore.p12}
  #  key-store-password: ${KEYSTORE_PASSWORD:soMe_StrOng12_PaSS}
  #  key-alias: ${KEYSTORE_ALIAS:eureka}
  #  trust-store: ${TRUSTSTORE:src/main/resources/eureka.truststore.p12}
  #  trust-store-password: ${TRUSTSTORE_PASSWORD:soMe_StrOng12_PaSS}
  #  enabled: true
  #  client-auth: none

eureka:
  instance:
    hostname: ${springboot.app.name:eureka-serviceregistry}
    prefer-ip-address: true
    non-secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${server.port}/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF